### ISSUE TITLE
Turn off WiFi after run (if it was turned on by pinpoint)

### ISSUE THREAD

**Issue by fridomac** [clburlison/pinpoint#18]
This feature would be really useful for me (WiFi is turned off on all of my machines, would only be turned on for the pinpoint run).

Any thoughts on that?

Bye, Frido.

**Comment by clburlison** [comment]
The ability to do that is pretty easy. I'll see what it takes to write that
up.

On Tue, Mar 8, 2016 at 4:50 AM fridomac <notifications@github.com> wrote:

> This feature would be really useful for me (WiFi is turned off on all of
> my machines, would only be turned on for the pinpoint run).
>
> Any thoughts on that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clburlison/pinpoint/issues/18>.
>
-- 
Clayton Burlison
@clburlison
https://clburlison.com

**Comment by clburlison** [comment]
Hey @fridomac I've added the ability to disable the wireless interface if pinpoint previously enabled it. To keep with the current behavior I made another key: `DisableWireless`. 

Documentation: https://github.com/clburlison/pinpoint/wiki/Preferences#supported-keys
Sample Profile: https://github.com/clburlison/pinpoint/blob/master/examples/pinpoint-wireless-handling.mobileconfig

I'll hopefully be pushing out a new release of pinpoint soon. If you want to build yourself and test you can do so with:

`git clone https://github.com/clburlison/pinpoint.git pinpoint && cd $_ && make pkg`

**Comment by fridomac** [comment]
Thank you for implementing this, really great. Will test it in the next few days....
