### ISSUE TITLE
Sierra support

### ISSUE THREAD

**Issue by clburlison** [clburlison/pinpoint#21]
Apple has updated the `locationd` daemon in Sierra. So pinpoint needs to be updated to support these changes. If doing an upgrade from 10.11 to 10.12 pinpoint will continue to work. 

It would likely be best if I can reverse Apple's private framework and add the python binary using the same steps Apple is using. Will need to investigate.

**Comment by clburlison** [comment]
The `cdhash` in `clients.plist` is no longer created in Sierra so it falls back to 10.10 style formatting which is correct. The root issue is I'm unable to start/stop Location Services with: `sudo launchctl load /System/Library/LaunchDaemons/com.apple.locationd.plist`

**Comment by clburlison** [comment]
And what I've been working on for 24 days just started working. Can others running 10.12 please test the above `launchctl` commands and let me know if it does properly disable and then re-enable Location Services. You'll need to close and relaunch System Preferences for it to reload the settings.

**Comment by bochoven** [comment]
Confirmed to be working on 10.12.1 Beta (16B2338c):

```
sudo launchctl unload /System/Library/LaunchDaemons/com.apple.locationd.plist
```
Location services are disabled
```
sudo launchctl load /System/Library/LaunchDaemons/com.apple.locationd.plist
```
Location services are enabled again

**Comment by pnerum** [comment]
I use 10.12 (16A323) and the launchctl commands work.

**Comment by clburlison** [comment]
Thanks guys. That helped narrow down my issue. Location Services on 10.12 has changed but the above isn't the hiccup.

**Comment by pnerum** [comment]
No thank you! Ill try out the new version that i’ve received with autopkg!
