### ISSUE TITLE
High Sierra Testing

### ISSUE THREAD

**Issue by 1JamesRyan** [clburlison/pinpoint#26]
Started testing with High Sierra.  Changed Line 134
    if not 8 <= int(os_vers()) <= 1**3**:
  
Changed Line 299
        if int(os_vers()) >= 1**3**:

Everything is working as intended.  Currently testing on a mac mini with High Sierra Beta 3.

**Comment by clburlison** [comment]
That's good to know. Did you allow pinpoint to enable location services and add python to the allow list? or was this a machine that was upgraded from 10.12?

**Comment by rogercrawford** [comment]
Just to add, although you're probably aware. Working with Beta 9, same two lines changed as above. Location Services were already enabled, Python had to be allowed access. Can't get Google lookup to work but Apple lookup is working fine. High Sierra was an upgrade from a clean install of Sierra.

**Comment by paul-cossey** [comment]
Does anyone have a way of enabling Pinpoint in location services via a script? My googling's only got me as far as enabling location services but not any Apps.

**Comment by rogercrawford** [comment]
#!/bin/bash

## Unload locationd
launchctl unload /System/Library/LaunchDaemons/com.apple.locationd.plist

## Write enabled value to locationd plist
defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd LocationServicesEnabled -int 1

## Fix Permissions for the locationd folder
chown -R _locationd:_locationd /var/db/locationd

## Reload locationd
launchctl load /System/Library/LaunchDaemons/com.apple.locationd.plist

exit 0
I use this to enable Sierra machines after imaging, I haven’t tested on High Sierra but IIRC they’ve put it under System Integrity Protection and it may not work. 

Regards,
Roger

**Comment by clburlison** [comment]
@paul-cossey Pinpoint should enable python but currently doesn't due to a bug #24 

@rogercrawford the Pinpoint code will do and enable Location Services so the above bash script shouldn't be required.

As for this current issue of High Sierra not working I should have an updated preview build uploaded in a few hours. I might need help testing the preview on 10.12 and earlier.

**Comment by clburlison** [comment]
Please test the latest pre-release and provide feedback https://github.com/clburlison/pinpoint/releases/tag/v2.0.0beta1

**Comment by rogercrawford** [comment]
Thanks Clayton. I’ll give this a shot on a group of test users here. 

Regards,
Roger

**Comment by paul-cossey** [comment]
Thanks, guys. I'll give the pre-release a test today ands report back.

 :-)
