### ISSUE TITLE
Handling ssid scanning exception

### ISSUE THREAD

**Issue by clburlison** [clburlison/pinpoint#34]
It's unclear if this is just a bug on 10.13 but I've managed to get `airport` command to give bad data multiple times tonight. This might be due to the very active wifi area that I'm in but Apple shouldn't give an incomplete file. 😞 

https://github.com/clburlison/pinpoint/blob/feaafc68e2479526ff259b1322afa17db8063454/pkgroot/Library/Application%20Support/pinpoint/bin/pinpoint#L538-L540

**Comment by danner26** [comment]
This happened to me many time. On campus, we will have machines that cannot report data because printer wifi networks cause issues (the stupid HP DIRECT wifi signals). Not sure if some have carriage returns or something, but during the airport scan the xml fetched will quit halfway.

**Comment by clburlison** [comment]
So this issue is just to track the hard crash. pinpoint should read the exception and write out an error.

I'm pretty sure it isn't a carriage return issue simply the `airport` command not being written in a way that it can handle that many SSIDs. I was able to replicate this a few times without pinpoint by calling:

```bash
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -s --xml 
```
 
It does look like I can replace the airport subprocess call with code from the Core WLAN framework. https://developer.apple.com/documentation/corewlan/cwinterface?language=objc That however it going to take a bit of time to write up and test.

**Comment by clburlison** [comment]
Switching to CoreWLAN is going to be the better solution. I have a mock up working so I'll switch to that in the next release.
